server:
  port: 9080

spring:
  datasource:
    url: 'jdbc:h2:file:~/admsvc'
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: ALWAYS


logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html